services:
  - type: web
    runtime: static
    name: proofmark
    rootDir: .
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
